### ISSUE TITLE
Binary firmware files

### ISSUE THREAD

**Issue by l4rth** [jpallister/stm32f4-energy-monitor#8]
Is it possible to download a binary firmware file, I have tried to compile it for several hours now and it won't work. I tried it in a blank system with the readme, and the linked workshop, both failed with 

```
energy_monitor.c:2:37: fatal error: libopencm3/stm32/f4/rcc.h: No such file or directory
 #include <libopencm3/stm32/f4/rcc.h>
```

**Comment by Jim-Walk** [comment]
Hi, I'm having the same problem. How did you solve it?

**Comment by ghost** [comment]
I'm having exactly the same problem. Has anyone figured out to solve it?

**Comment by l4rth** [comment]
There is somewhere a binary file in the project, which I used, I think it is called energy_mointor.

Although I haven't got It working otherwise.

**Comment by ghost** [comment]
/src/firmware/energy_monitor for anyone else wondering. I wish I'd noticed it earlier.

Thank you for your comment b14ckkn19ht

**Comment by l4rth** [comment]
No Problem, this info is mandatory as part of the documentation I think, maybe the owner of this repo can add it
